### ISSUE TITLE
can this be made to work with python3?

### ISSUE THREAD

**Issue by mals14** [Jaymon/enno#7]
thank you for sharing your work. stumbled upon this yesterday, and it looks so much better than what Evernote put out :)

tried to install it, but pip3 would not install it. presumably because it relies on Evernote library which in turn is python2.0 compatible.

I did install Evernote's python3 compatible library from GitHub. wondering if I can now use Enno because their python3 library seems to have similar Types and functions etc.

Thank you!

**Comment by Jaymon** [comment]
Try it out. The code is designed to be more or less python 3 compatible, at least I've listed python 3 compatibility in the [setup.py](https://github.com/Jaymon/enno/blob/master/setup.py#L47) so it might be as simple as changing the `evernote` library name for python 3 installation.

**Comment by mals14** [comment]
Ok will try and thank you for replying!

For now, I had put aside the automation but will try and look into it again soon.

**Comment by Jaymon** [comment]
I happened to have a temp python3 installation I could test on today, I fixed the installation issue in https://github.com/Jaymon/enno/commit/6bdb885a673ab0ade06f4595c9a3a53e7fe2995f but I didn't run it, but it should at least install now. 

I'm not going to put this on Pypi yet until I have a moment to make sure it's actually working, but you can install it directly from the repo:

    $ pip install -U "git+https://github.com/jaymon/enno#egg=enno"

That should hopefully put you in a good position when you look at it again

**Comment by mals14** [comment]
Thank you and will do!
